version: '2'
services:
    it-pywikibot:
        image: taueres/pywikibot-itwiki:1.0
        volumes:
            - .:/root/it-pywikibot
            - ../pywikibot-itwiki-config:/root/config-pywikibot
            - ../pywikibot-itwiki-config:/root/data
            - ../pywikibot-itwiki-config:/root/config-custom
        environment:
            - ITWIKI_PYWIKIBOT_DEBUG=1
            - ITWIKI_PYWIKIBOT_LANGUAGE_FILE=/root/data/language-data
            - ITWIKI_PYWIKIBOT_REVISION_FILE=/root/data/revision
            - ITWIKI_PYWIKIBOT_CONTINUE_TOKEN_FILE=/root/data/continue-token
            - ITWIKI_PYWIKIBOT_DATABASE_CONFIG_FILE=/root/config-custom/database-config.json
            - PYWIKIBOT2_DIR=/root/config-pywikibot
            - PYTHONPATH=/root/pywikibot
