version: '2'
services:
    it-pywikibot:
        build: .
        volumes:
            - .:/root/it-pywikibot
            - ../pywikibot-itwiki-config:/root/config-pywikibot
            - ../pywikibot-itwiki-config:/root/data
            - ../pywikibot-itwiki-config:/root/config-custom
        environment:
            - TAUERBOT_DEBUG=1
            - TAUERBOT_LANGUAGE_FILE=/root/data/language-data
            - TAUERBOT_REVISION_FILE=/root/data/revision
            - TAUERBOT_CONTINUE_TOKEN_FILE=/root/data/continue-token
            - TAUERBOT_DATABASE_CONFIG_FILE=/root/data/database-config.json
            - PYWIKIBOT2_DIR=/root/config-pywikibot
            - PYTHONPATH=/root/pywikibot
